# Generated by Django 5.2.11 on 2026-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='evidence_image',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='status_message',
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_points',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='last_violation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='camera',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='camera',
            name='risk_level',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
