# Generated by Django 5.2.8 on 2026-03-01 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_remove_alert_evidence_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
